### ISSUE TITLE
extension : menu et envoi de données aux scripts

### ISSUE THREAD

**Issue by puitgfr** [LeaL33/projetTuteurePrestobois#3]
Je pense que la clé [commands](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/commands) du [manifest.json](https://developer.mozilla.org/fr/Add-ons/WebExtensions/manifest.json) doit permettre de faire ce qu'on veut.

[Anatomy of a WebExtension](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Anatomy_of_a_WebExtension#Background_scripts) fait le tour de la question.

Il y a aussi [webextensions-examples](https://github.com/mdn/webextensions-examples) qui peut vous aider.

**Comment by CouroubleThomas** [comment]
Bonjour, j'ai finalement réussi sans utiliser commands mais avec sendMessage et onMessage, avec un script de background pour faire le lien

**Comment by puitgfr** [comment]
Ok, parfait, je viens de tester, ça fonctionne parfaitement.

Est-il possible que la checkbox « Récapitulatif de commande » ait la sémantique suivante :
- si  aucun sous-menu n'est coché, elle n'est pas cochée
- si tous les sous-menus sont cochés, elle est cochée (choix par défaut)
- si un des sous-menu est coché, elle est cochée en filigrane,
- si on la coche, ça coche tous les sous-menus,
- si on la décoche, ça décoche tous les sous-menus.

**Comment by CouroubleThomas** [comment]
J'ai réalisé ces modifications, je ne sais pas trop ce qu'est filigrane du coup j'ai utilisé la propriété indeterminate.

De plus j'ai fait le choix que lorsque l'on clique sur la checkbox1 alors qu'elle est indéterminée, on la considère qu'elle n'est pas checked donc elle le devient sur le click.

Dîtes moi si cela vous convient

**Comment by puitgfr** [comment]
propriété indeterminate : c'est exactement ça.
determinate sur le click : ok, parfait
