### ISSUE TITLE
Prochaine réunion

### ISSUE THREAD

**Issue by puitgfr** [LeaL33/projetTuteurePrestobois#4]
Jeudi 1/06, 16h30.

D'ici là, voila ce qu'on avait dit à la réunion précédente :
- [x] corriger problème unité dans calcul de poids
- [x] ajouter colonne calcul volume
- [x] coder un parsing du récap commande pour détecter les options « clé : valeur »
  - [x] en déduire calcul contenance (ex commande n°18535878)
  - [x] prévoir affichage « non supporté » pour clés non reconnues
- [x] trouver solution pour menus de l'extension

J'ajoute quelques points pour le bon de commande :
- [x] inverser colonnes long et larg
- [x] justifier à droite colonnes ép, larg, long et qté
- [x] corriger bug unité dans colonne larg (tout en mm)
- [x] reprendre style section pour titre « bon de commande » (comme « Détail »)
- [x] reprendre style produit (comme dans la colonne Article du tableau « Détail »)

pour « Mode de livraison » :
- [x] ajouter « ligne longueur max » en m
- [x] ajouter ligne « encombrement max » = longueur max + largeur max + épaisseur max (en m)
      si encombrement max > 2m, la ligne est en rouge
- [x] bouton « enregistrer Colissimo » actif ssi poids < 30 kg
- [x] améliorer affichage (volume total, poids total, longueur max et encombrement max dans tableau à 2 colonnes)

et pour le tableau détail :
- [x] indiquer aussi poids total (et volume) sur ligne « Sous-total TTC»

EDIT :
- [ ] généraliser le tout aux commandes sur devis, via requêtes xmlhttprequest

**Comment by LeaL33** [comment]
Merci, ça va nous aider à nous organiser ! :)

**Comment by CouroubleThomas** [comment]
Bonjour, qu'entendez vous par "corriger bug unité dans colonne larg (tout en mm)", il me semble que cela fonctionne ?

![image](https://cloud.githubusercontent.com/assets/16308447/26449758/55db06fe-4154-11e7-9ab1-6c66894cda8e.png)

**Comment by puitgfr** [comment]
Ok, impeccable maintenant (j'avais testé une version antérieure). Bonne idée d'ajouter la densité. Bien vu le delta du poids quand c'est trop lourd pour le colissimo.

Coté des commandes sur devis (j'ai oublié de le mettre dans ma liste du 1er post, je le rajoute), qu'est-ce que ça donne avec les xmlhttprequest ?

**Comment by CouroubleThomas** [comment]
Je n'ai pas trop regardé pour le moment, je pense réaliser les 3 points sur les clés valeurs demain et je regarderai plus en détail xmlhttprequest mercredi et jeudi

**Comment by CouroubleThomas** [comment]
Pour contenance, on considère que l'article est un cube ?

**Comment by puitgfr** [comment]
xmlhttprequest : ok, pour mercredi et jeudi
contenance : on consière que c'est un cylindre.

**Comment by CouroubleThomas** [comment]
du coup pour un cylindre que dois je mettre dans le bon de commande ?

**Comment by puitgfr** [comment]
Juste la contenance : elle identifie de façon univoque le produit.

**Comment by CouroubleThomas** [comment]
Très bien, je commit dîtes moi ce que vous en pensez.
Si vous avez d'autres exemples de commande avec différentes clés je veux bien les voir

**Comment by puitgfr** [comment]
Ok, j'ai testé, c'est bien mais :
- [ ] calculer les 3 volumes en m3 (dans section mode de livraison, détail commande et volume total)
- [ ] vérifier calcul encombrement (voir ci-après)
Et là je vais vous embêter :
- [ ] remplacer les colonnes ép, larg et long par deux colonnes : contenance et teinte

Pour les bdc des commandes comportant des produits hétéroclites, le plus simple est de faire autant de tableaux que d'articles partageant les mêmes unités.

J'ai fait une commande comme celle-là pour que vous puissiez tester, c'est la n°18638329.
Il y aurait donc pour cette commande :
- un tableau pour la console, l'avivé et le carrelet (2 ou 3 dimensions communes ; la taille peut apparaître dans la colonne longueur, la section correspond à largeur x épaisseur, qui sont identiques pour les produits où n'est indiqué que la section),
- un tableau pour les packs d'huile (2 dimensions communes, la teinte et la contenance ; quand la teinte n'est pas précisée, c'est « naturelle ») 

Quand on affiche le récap de commande, on a bien la modale « affichage de : Console sapin/épicéa n'est pas supporté » ; bien.

On voit une erreur dans le calcul de l'encombrement et aussi dans masse et volume de « Pack huile écologique finition pigmentée », ce qui est normal, vous avez dû faire votre calcul en supposant que c'était toujours des ml. Je vais harmoniser tout ça en imposant dans la base de donnée que pour tous les produits ayant une contenance, celle-ci soit exprimée en l (vous pouvez modifier votre code en ce sens, dès que c'est fait je refait la même commande que la 18638329 pour tester).

**Comment by CouroubleThomas** [comment]
Bonjour, pouvez vous me préciser comment calculer le volume/poids pour console/carrelet
par exemple pour Console est ce que taille = longueur ? Pour Carrelet section = ?

**Comment by CouroubleThomas** [comment]
Je pense avoir trouvé pour carrelet, par contre pour console je n'ai aucune idée

**Comment by CouroubleThomas** [comment]
Serait il possible que les volumes soient exprimés en x.x et non x,x ? Je n'arrive pas à trouver de façon de convertir

**Comment by CouroubleThomas** [comment]
je viens de commit un premier jet, les valeurs ne sont probablement pas exactes (surtout pour console) mais je voudrai surtout votre avis sur la mise en forme

**Comment by puitgfr** [comment]
Ok, je vais regarder, mais je suis en exam aujourd'hui, donc pas avant ce soir. Pour les consoles, on ajustera en prenant une densité ah hoc. À vue de nez, vous pouvez prendre 1500 pour l'épicéa et 2000 pour le mélèze.

Aucun problème si vous voulez écrire les volumes sous la forme x.x (je pense qu'il existe de fonctions dites de localisation en js, mais pour l'instant on peut rester comme ça

**Comment by CouroubleThomas** [comment]
c'est pas tellement les densités c'est quelle est la formule du volume pour une forme comme celle là

en fait c'est dans la lecture des paramètres directement sur oxatis que l'on a une virgule

**Comment by puitgfr** [comment]
Ah ok. On fait comme si c'était un cube.

Je vais voir pour les paramètres, mais je ne crois pas avoir la main pour pouvoir faire des modifs à ce niveau

**Comment by CouroubleThomas** [comment]
Ok.

Ba finalement j'ai utilisé String.replace et ça marche bien.

Encore une question, pour l'encombrement max, (qui pour le moment est longueur + largeur + epaisseur), dans le cas d'un cylindre quelles sont les valeurs que je doit ajouter?

**Comment by CouroubleThomas** [comment]
Ah oui et aussi, dans la commande exemple on a 
![image](https://cloud.githubusercontent.com/assets/16308447/26635054/d199e4ae-4618-11e7-9f54-ae1e6881269d.png)

et si on regarde on voit que le code ne donne pas la même valeur de largeur. Laquelle est la bonne ?

**Comment by puitgfr** [comment]
Je viens juste de récupérer le dernier commit, je suis un peu débordé.

Pour l'encombrement, c'est longueur max + largeur max + épaisseur max, sachant que les dimensions max ne sont pas forcément atteintes par le même article.

Pour la densité de l'huile, prenez 1 sinon le pot de 350ml est très lourd !

Bien pour les tableaux séparé (un </br> supplémentaire entre chaque). Il faudrait fusionner les carrelets avec les avivés (car ça sera le même fournisseur), autrement dit détecter que quand le couple clé : valeur est section : x, on transforme en largeur : x et épaisseur : x.

Pour les consoles, je pense qu'il y a un bug dans la bd. Pour l'instant, on laisse comme ça.

À toute à l'heure
